### ISSUE TITLE
Relationship between pyexcel modules

### ISSUE THREAD

**Issue by piskvorky** [pyexcel/pyexcel-odsr#5]
The README says:

> Differring from pyexcel-ods and pyexcel-ods3 in handling ods file, this library could read partial content from a huge ods file.

I'm unclear about the relationships between the pyexcel modules. Why / when should I use `pyexcel-ods` vs `pyexcel-ods3` (is there a `pyexcel-ods2`?) vs `pyexcel-odsr`?

Or asked differently: why *wouldn't* I want to be able to "read partial content from a huge ODS file"? What's the disadvantage of `pyexcel-odsr` (or `pyexcel-ods3` or `pyexcel-ods`)?

Also, I see the different modules are updated at different rates. The latest commit in `pyexcel-odsr` is from 2017. What's the maintenance process, how are dependency upgrades (xlrd, openpyxl, messytables?) reflected in the various overlapping pyexcel modules?

Many thanks.

**Comment by chfw** [comment]
first of all: there is no pyexcel-ods2

both pyexcel-ods and pyexcel-ods3 reads all into memory and start emitting data whereas pyexcel-odsr would emit data while parsing ods file.

pyexce-ods uses odfpy and pyexcel-ods3 uses pyexcel-ezodf.

Each pyexcel-xxx libraries have its independent development route. Unless there is a bug or a new feature, a new release will be made. Otherwise, all pyexcel-xxx plugins are provided with the best knowledge to date.

In general, you will need to read pyexcel's README to understand its architecture.

**Comment by piskvorky** [comment]
Thanks. I'm no nearer understanding which module I should use to read ODS though.

Beyond the streaming property of `pyexcel-odsr`, which is nice… so I guess I just forget about the other two?

**Comment by chfw** [comment]
pyexcel-odsr does only 'read' as long as you are happy with its read functionality. the other two are the backup reader for you. 

When it comes to 'write' an ods file, you will then have to choose one of the other two.

**Comment by chfw** [comment]
I forgot to mention another library, yet to be released, https://github.com/pyexcel/pyexcel-odsw, which does only ods 'write'. so you got three options for writing an ods.

**Comment by piskvorky** [comment]
Spoilt for choice! A fool-proof diagram of **"Use this module when… Don't use this module when…"** would be nice. A TL;DR of advantages / disadvantages of the alternatives:

| optional module       | pros                                       | cons                  | use when… |
|--------------|--------------------------------------------|-----------------------|---------|
| pyexcel-odsr | stream **from** huge ODS files efficiently | no writing            | you want to only **read** ODS |
| pyexcel-odsw | stream **to** huge ODS files efficiently   | no reading            | you want to only **write** ODS |
| pyexcel-ods  | read and write ODS files                   | loads all sheets in memory; dependencies no longer maintained (example)                    | you want to read and write ODS |
| pyexcel-ods3 | read and write ODS files                   | loads all sheets in memory  | ?? why are there two modules doing apparently the same thing? |

This is an awesome and useful lib. Just the different READMEs appear mostly copy-pasted, so as a user it's not easy to navigate what's what (and why).

Just an idea :)

**Comment by chfw** [comment]
I will take your advice.

**Comment by chfw** [comment]
by the way, here is the similar table you referred to:

http://docs.pyexcel.org/en/latest/#id7

I will complement it with a 'shopping guide'.
